link_relation_names: ["arm"]

link_relation:
  arm:
    joint_names: ["axis0", "axis1", "axis2"]

#   lowerarm_left:
#     joint_names: ["elbow_left_axis0","elbow_left_axis1"]
#
#   hand_left:
#     joint_names: ["wrist_left_axis0", "wrist_left_axis1", "wrist_left_axis2"]
#
#   head:
#     joint_names: ["head_axis0", "head_axis1", "head_axis2"]
#
#   upperarm_right:
#     joint_names: ["right_axis0", "right_axis1", "right_axis2"]
#
#   lowerarm_right:
#     joint_names: ["elbow_right_axis0","elbow_right_axis1"]
#
#   hand_right:
#     joint_names: ["wrist_right_axis0", "wrist_right_axis1", "wrist_right_axis2"]
