joint_dt: [ 0.2,0.2,0.2, #,
            0.2,0.2,
            0.2,0.2,0.2,
            0.2,0.2,0.2,
            0.2,0.2,0.2,
            0.2,0.2]
            # 0.2,0.2,0.2 ]
joint_kp: [ 50.0,50.0,0.0,
            50.0,50.0,
            50.0,50.0,50.0,
            50.0,50.0,50.0,
            50.0,50.0,0.0,
            50.0,50.0]
            # 50.0,50.0,50.0 ]
joint_kd: [ 0.0,0.0,0.0,
            0.0,0.0,
            0.0,0.0,0.0,
            0.0,0.0,0.0,
            0.0,0.0,0.0,
            0.0,0.0] #,
            # 0.0,0.0,0.0 ]
