#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
shoulder_left_axis0:
  joint: shoulder_left_axis0
  type: cardsflow/kindyn/CableLengthController
shoulder_left_axis1:
  joint: shoulder_left_axis1
  type: cardsflow/kindyn/CableLengthController
shoulder_left_axis2:
  joint: shoulder_left_axis2
  type: cardsflow/kindyn/CableLengthController
elbow_left_axis0:
  joint: elbow_left_axis0
  type: cardsflow/kindyn/CableLengthController
elbow_left_axis1:
  joint: elbow_left_axis1
  type: cardsflow/kindyn/CableLengthController
shoulder_right_axis0:
  joint: shoulder_right_axis0
  type: cardsflow/kindyn/CableLengthController
shoulder_right_axis1:
  joint: shoulder_right_axis1
  type: cardsflow/kindyn/CableLengthController
shoulder_right_axis2:
  joint: shoulder_right_axis2
  type: cardsflow/kindyn/CableLengthController
elbow_right_axis0:
  joint: elbow_right_axis0
  type: cardsflow/kindyn/CableLengthController
elbow_right_axis1:
  joint: elbow_right_axis1
  type: cardsflow/kindyn/CableLengthController
head_axis0:
  joint: head_axis0
  type: cardsflow/kindyn/CableLengthController
head_axis1:
  joint: head_axis1
  type: cardsflow/kindyn/CableLengthController
head_axis2:
  joint: head_axis2
  type: cardsflow/kindyn/CableLengthController