head:
  motor_ids: [20,21,22,23,24,25]
  use_motor_config: true
shoulder_left:
  motor_ids: [0,1,2,3,4,5,6,7,16,17]
  use_motor_config: true
shoulder_right:
  motor_ids: [8,9,10,11,12,13,14,15,18,19]
  use_motor_config: true
