head:
  motor_ids: [20,21,22,23,24,25]
  use_motor_config: true
  endeffector: "head"
shoulder_left:
  motor_ids: [0,1,2,3,4,5,6,7,17]
  use_motor_config: true
  endeffector: "hand_left"
shoulder_right:
  motor_ids: [8,9,10,11,12,13,14,15,19] # 18
  use_motor_config: true
  endeffector: "hand_right"
wrist_left:
  motor_ids: [26,27,28,29,30,31]
  use_motor_config: true
  endeffector: "hand_left"
wrist_right:
  motor_ids: [32,33,34,35,36,37]
  use_motor_config: true
  endeffector: "hand_right"
hand_right:
  motor_ids: [42,43,44,45]
  use_motor_config: true
  endeffector: "hand_right"
hand_left:
  motor_ids: [38,39,40,41]
  use_motor_config: true
  endeffector: "hand_left"
spine:
  motor_ids: [47, 48, 49, 50] # 46,50,51]
